logging:
  level:
    org:
      hibernate:
        SQL: INFO
server:
  error:
    whitelabel:
      enabled: true
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerce?createDatabaseIfNotExist=true
    password: 123456
    username: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  mvc:
    throw-exception-if-no-handler-found: true
security:
  signing-key: MjWP5L7CiD
